version: "3"
services:
  web:
    image: ultinate/javawebapp:0.0.1
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "4000:80"
    networks:
      - webnet
  robot:
    image: ypasmk/robot-framework
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "4444:4444"
    networks:
      - webnet
    volumes:
      - "./output:/output"
      - "./suites:/suites"
      - "./scripts:/scripts"
      - "./reports-compose:/reports"
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:


# -e USERNAME="Ipatios Asmanidis"
# --net=host 
# --security-opt seccomp:unconfined 
# --shm-size "256M" \
